banking/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('bankingapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankingapp/urls.py
from django.urls import path,include
from . import views
app_name='bankingapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/',views.login,name='login'),
    path('services/',views.services,name='services'),
    path('logout/',views.logout,name='logout'),
    path('details',views.details,name='details'),
    path('transfer',views.money,name='transfer'),
    path('registration_success',views.registration_success,name='registration_success'),
]

bankingapp/models.py
from django.db import models

# Create your models here.

bankingapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.utils import timezone
from datetime import datetime


# Create your views here.
def home(request):
    return render(request, 'home.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['fname']
        last_name = request.POST['lname']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already exists")
                return redirect('bankingapp:signup')
            else:
                user = User.objects.create_user(username=username, password=password, first_name=first_name,
                                                last_name=last_name, email=email)

                user.save()
                print('User created')
                return redirect('bankingapp:login')

        else:
            messages.info(request, "password not matched")
            return redirect('bankingapp:signup')

    return render(request, 'signup.html')



def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return render(request,'home.html')
        else:
            messages.info(request, "invalid username or password")
            return redirect('bankingapp:login')

    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def services(request):
    return render(request,'services.html')

def details(request):
    if request.method == 'POST':
        fname = request.POST['fname']
        lname = request.POST['lname']
        bankname = request.POST['bankname']
        acnumber = request.POST['acnumber']
        ifsc = request.POST['ifsc']
        zip = request.POST['zip']
        address = request.POST['address']
        city = request.POST['city']
        district = request.POST['district']
        branch = request.POST['branch']
        dob = request.POST['dob']
        age = int(request.POST['age'])
        phone = request.POST['phone']
        email = request.POST['email']
        type_ac = request.POST['account-type']
        gender=request.POST['gender']
        ms = ['Debit Card', 'Credit Card', 'Cheque Book']
        details = request.POST.getlist('materials')

        # Your validation logic here

        if len(ifsc) != 11 or len(acnumber) < 8 or len(acnumber) > 12 or len(zip) != 6 or len(phone) != 10:
            print('validation error')
            return redirect('bankingapp:details')
        else:
            dob_input = request.POST['dob']
            age_input = int(request.POST['age'])

            # Validate Date of Birth and Age

            try:
                dob = datetime.strptime(dob_input, '%Y-%m-%d').date()
                current_date = timezone.now().date()
                # gender = request.POST['gender']

                calculated_age = current_date.year - dob.year - (
                            (current_date.month, current_date.day) < (dob.month, dob.day))
                if age_input == calculated_age:
                    # register = Register(fname=fname, address=address, lname=lname, city=city, zip=zip,
                    #                     district=district, branch=branch, dob=dob, age=age, bankname=bankname,
                    #                     acnumber=acnumber, ifsc=ifsc, gender=gender, phone=phone, email=email,
                    #                     type_ac=type_ac, details=details)
                    # register.save()
                    # print(register)
                    return render(request, 'registration_success.html')
                else:
                    return redirect('bankingapp:details')
            except:
                return redirect('bankingapp:details')

    return render(request,'details.html')

def money(request):
    return render(request,'money_transfer.html')
def registration_success(request):
    return render(request,'registration_success.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <script src="https://kit.fontawesome.com/808186c62d.js" crossorigin="anonymous"></script>
</head>
<body>
{% block content %}
{% endblock %}

{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Mobile banking
{% endblock %}
{% block content %}
<div>
    <div>
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark" style="height:75px;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Mobile Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bankingapp:home' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Branches
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Federal_Bank">Thiruvananthapuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Canara_Bank">Alappuzha</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/State_Bank_of_India">Ernakulam</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/South_Indian_Bank">Malappuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/ICICI_Bank">Kozhikode</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kotak_Mahindra_Bank">Thrissur</a></li>
                        </ul>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <h6 class="pt-2" style="color:white">Hello {{user.username}}   </h6>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:logout' %}"><button type="button" class="btn btn-primary" >Logout</button></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:login' %}"><button type="button" class="btn btn-primary" >Login</button></a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>
<div>
    <div class="mt-5">
        <center>
            <img src="{% static 'img/WelcomeBanner.png' %}" width="90%" height="400px">
        </center>
    </div>
</div>
<div class="mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/bank.jpg' %}" class="card-img-top" alt="bank details">
                   <div class="card-body">
                       <h4 class="card-title">Bank details</h4>
                       <p class="card-text"><b>Add Your Bank Details</b></p>
                       <a href="{% url 'bankingapp:details' %}" class="btn btn-primary">Bank Details</a>
                   </div>
               </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/services.png' %}" class="card-img-top" alt="services">
                   <div class="card-body">
                       <h4 class="card-title">Services</h4>
                       <p class="card-text"><b>Online Payment Services</b></p>
                       <a href="{% url 'bankingapp:services' %}" class="btn btn-primary">Services</a>
                   </div>
               </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/money transfer.png' %}" class="card-img-top" alt="money transfer">
                   <div class="card-body">
                       <h4 class="card-title">Money Transfer</h4>
                       <p class="card-text"><b>Transfer money to other bank</b></p>
                       <a href="{% url 'bankingapp:transfer' %}" class="btn btn-primary">Bank Details</a>
                   </div>
               </div>
            </div>

        </div>
    </div>
</div>
<hr>
{% endblock %}

templates/login.html
{%  extends 'base.html' %}
{% load static %}
{% block title %}
Login
{% endblock %}
{% block content %}
<div>
    <div>
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark" style="height:75px;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SBI Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'bankingapp:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:services' %}">Services</a>
                        </li>

                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Branches
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
                        </ul>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <h6 class="pt-2" style="color:white">Hello {{user.username}}   </h6>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:logout' %}"><button type="button" class="btn btn-primary" >Logout</button></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:login' %}"><button type="button" class="btn btn-primary" >Login</button></a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="login">
    <center>
    <div class="pt-5">
        <h1>Login</h1>
        <div class="lo-box">
            <form action="" method="post">
            {% csrf_token %}
                <input class="box" type="text" name="username" placeholder="Enter user name">
                <input class="box" type="password" name="password" placeholder="Enter password">
                <input type="submit" value="Login" class="btn btn-primary btn-submit">
            </form>
            <hr>
            <p class="p-login pb-2">New user?<a class="here" href="{% url 'bankingapp:signup' %}"><b>Register</b></a>Now</p>
        </div>
    </div>
    </center>
</div>
{% endblock %}

templates/money_transfer.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Money Transfer
{% endblock %}
{% block content %}

<div>
    <div>
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark" style="height:75px;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SBI Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'bankingapp:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:services' %}">Services</a>
                        </li>

                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Branches
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
                        </ul>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <h6 class="pt-2" style="color:white">Hello {{user.username}}   </h6>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:logout' %}"><button type="button" class="btn btn-primary" >Logout</button></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:login' %}"><button type="button" class="btn btn-primary" >Login</button></a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="details pt-5">
    <div class="container-fluid p-4">
        <div class="row">
            <form action="" method="post">
            {% csrf_token %}
                <div class="row form-row">
                    <div class="form-group col-12 col-sm-6 col-md-4 col-lg-6">
                        <label for="firstname">First Name</label>
                        <input type="text" class="form-control" name="fname" placeholder="First Name" required>
                    </div>
                    <div class="form-group col-12 col-sm-6 col-md-4 col-lg-6">
                        <label for="lastname">Last Name</label>
                        <input type="text" class="form-control" name="lname" placeholder="Last Name" required>
                    </div>
                    <div style="height:15px; width:100%"></div>
                    <div class="row form-row">
                        <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
                            <label for="bankname">Bank Name</label>
                            <input type="text" class="form-control" name="bankname" placeholder="Bank Name" required>
                        </div>
                        <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
                            <label for="IFSC">IFSC code</label>
                            <input type="text" class="form-control" id="ifsc" name="ifsc" placeholder="IFSC Code" required>
                        </div>
                        <div style="height:15px; width:100%"></div>
                        <div class="row form-row">
                            <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
                                <label for="accountnumber">Account Number</label>
                                <input type="number" class="form-control" id="acnumber" name="acnumber" placeholder="Account Number" required>
                            </div>
                            <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6">
                                <label for="Amount">Amount</label>
                                <input type="number" class="form-control" id="amount" name="amount" placeholder="Amount" required>
                            </div>
                        </div>
                        <div style="height:40px; width:100%;"></div>

                            <center>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit" onclick="submitting()">Transfer</button>
                                </div>
                            </center>
                            <div style="height:30px; width:100%;"></div>
                        </div>
                </form>
        </div>
    </div>
</div>
<hr>

{% endblock %}

templates/registration_success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
back to home
{% endblock %}
{% block content %}

<div>
    <div>
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark" style="height:75px;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SBI Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'bankingapp:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:services' %}">Services</a>
                        </li>

                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Branches
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
                        </ul>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <h6 class="pt-2" style="color:white">Hello {{user.username}}   </h6>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:logout' %}"><button type="button" class="btn btn-primary" >Logout</button></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:login' %}"><button type="button" class="btn btn-primary" >Login</button></a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

<div>
    <div style="width:100%; height:450px; text-align:center">
        <div style="padding:80px;">
            <h3>Successfully Submitted!!</h3>
        </div>
        <div>
            <a href="{% url 'bankingapp:home' %}"><button type="button" class="btn btn-primary">Back to Home</button> </a>
        </div>
    </div>
</div>


{% endblock %}

templates/services.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Services
{% endblock %}
{% block content %}
<div>
    <div>
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark" style="height:75px;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">SBI Banking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'bankingapp:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link active" href="{% url 'bankingapp:services' %}">Services</a>
                        </li>

                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Branches
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
                        </ul>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <h6 class="pt-2" style="color:white">Hello {{user.username}}   </h6>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:logout' %}"><button type="button" class="btn btn-primary" >Logout</button></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'bankingapp:signup' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'bankingapp:login' %}"><button type="button" class="btn btn-primary" >Login</button></a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/mobile-recharge.jpg' %}" class="card-img-top" alt="mobile recharge">
                   <div class="card-body">
                       <h4 class="card-title">Mobile Recharge</h4>
                       <a href="https://pay.google.com" class="btn btn-primary">Recharge</a>
                   </div>
               </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/electricity bill.png' %}" class="card-img-top" alt="electricity bill">
                   <div class="card-body">
                       <h4 class="card-title">Electricity bill</h4>
                       <a href="https://pay.google.com" class="btn btn-primary">Electricity bill</a>
                   </div>
               </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/money transfer.png' %}" class="card-img-top" alt="money transfer">
                   <div class="card-body">
                       <h4 class="card-title">Online Shopping</h4>
                       <a href="https://www.amazon.in" class="btn btn-primary">Shopping</a>
                   </div>
               </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/rent.jpg' %}" class="card-img-top" alt="rent">
                    <div class="card-body">
                        <h4 class="card-title">Pay Rent</h4>
                        <a href="https://pay.google.com" class="btn btn-primary">Rent</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/loan.png' %}" class="card-img-top" alt="loan">
                    <div class="card-body">
                        <h4 class="card-title">Loan</h4>
                        <a href="#" class="btn btn-primary">Loan</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!--<div class="pt-5 ps-3">-->

<!--    <h1>Our services</h1>-->
<!--    <ul>-->
<!--        <li>Deposit Services</li>-->
<!--        <li>Loan Services</li>-->
<!--        <li>Electronic Banking</li>-->
<!--        <li>Payment Services</li>-->
<!--        <li>Investment Services</li>-->
<!--        <li>Insurance Services</li>-->
<!--        <li>Retirement Planning</li>-->
<!--        <li>International Banking</li>-->
<!--        <li>Safety Deposit Boxes</li>-->
<!--        <li>Financial Advisory Services</li>-->
<!--        <li>Educational Services</li>-->
<!--        <li>Corporate Banking Services</li>-->
<!--    </ul>-->

</div>
{% endblock %}